[2021-11-15 18:02:05,244] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T18:02:03.696712+00:00 [queued]>
[2021-11-15 18:02:05,257] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T18:02:03.696712+00:00 [queued]>
[2021-11-15 18:02:05,257] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:02:05,257] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-15 18:02:05,257] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-15 18:02:05,274] {taskinstance.py:1262} INFO - Executing <Task(PostgresOperator): ingest_to_dwh> on 2021-11-15 18:02:03.696712+00:00
[2021-11-15 18:02:05,279] {standard_task_runner.py:52} INFO - Started process 2010 to run task
[2021-11-15 18:02:05,282] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'covid_ingestion', 'ingest_to_dwh', 'manual__2021-11-15T18:02:03.696712+00:00', '--job-id', '169', '--raw', '--subdir', 'DAGS_FOLDER/covid_ingestion.py', '--cfg-path', '/tmp/tmp43k_345_', '--error-file', '/tmp/tmpslxsz_fj']
[2021-11-15 18:02:05,283] {standard_task_runner.py:77} INFO - Job 169: Subtask ingest_to_dwh
[2021-11-15 18:02:05,325] {logging_mixin.py:109} INFO - Running <TaskInstance: covid_ingestion.ingest_to_dwh manual__2021-11-15T18:02:03.696712+00:00 [running]> on host 6f9154c92b39
[2021-11-15 18:02:05,418] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=covid_ingestion
AIRFLOW_CTX_TASK_ID=ingest_to_dwh
AIRFLOW_CTX_EXECUTION_DATE=2021-11-15T18:02:03.696712+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-15T18:02:03.696712+00:00
[2021-11-15 18:02:05,427] {base.py:79} INFO - Using connection to: id: postgres_dwh. Host: postgres-dwh, Port: 5432, Schema: None, Login: ***, Password: ***, extra: {}
[2021-11-15 18:02:05,431] {dbapi.py:225} INFO - Running statement: 
            CREATE TABLE IF NOT EXISTS pet (
            pet_id SERIAL PRIMARY KEY,
            name VARCHAR NOT NULL,
            pet_type VARCHAR NOT NULL,
            birth_date DATE NOT NULL,
            OWNER VARCHAR NOT NULL);
          , parameters: None
[2021-11-15 18:02:05,432] {postgres.py:71} INFO - NOTICE:  relation "pet" already exists, skipping

[2021-11-15 18:02:05,446] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=covid_ingestion, task_id=ingest_to_dwh, execution_date=20211115T180203, start_date=20211115T180205, end_date=20211115T180205
[2021-11-15 18:02:05,494] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-15 18:02:05,528] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
